name: Daily Rudderstack Tests

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for accessing history for Allure reports

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Allure command-line
        run: npm install -g allure-commandline

      - name: Check Chrome version
        run: google-chrome --version

      - name: Install ChromeDriver
        run: npm install chromedriver@138.0.0 --save-dev

      - name: Clean up Chrome processes
        run: pkill -f chrome || true

      - name: Run tests
        run: npx wdio config/wdio.conf.js
        env:
          ENV: ${{ matrix.env }}

      - name: Load test report history
        if: always()
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: allure-history
        continue-on-error: true

      - name: Generate Allure report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean
          cp -r allure-history/. allure-report/history || true
        env:
          ALLURE_RESULTS_PATH: allure-results

      - name: Publish Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          keep_files: true # Preserve history for Allure reports

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.env }}
          path: allure-results

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.env }}
          path: allure-report