name: Daily Rudderstack Tests

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check Chrome version
        run: google-chrome --version

      - name: Install ChromeDriver
        run: npm install chromedriver@138.0.0 --save-dev

      - name: Clean up Chrome processes
        run: pkill -f chrome || true

      - name: Run tests
        run: npx wdio config/wdio.conf.js
        env:
          ENV: ${{ matrix.env }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.env }}
          path: allure-results